language: python
python:
    - "2.7"
addons:
    postgresql: "9.4"
    apt:
        packages:
            - python-gdal
            - p7zip-full
notifications:
    email: comses-dev@googlegroups.com
env: DB=postgres
before_script:
    - cd docker_config && ./source.py travis && source ./source.sh && cd ..
    - cp django/miracle/settings/travis_local.py.example django/miracle/settings/local.py
    - cd django && fab setup
install: 
    - pip install -r django/requirements/local.txt
script: fab coverage
after_success:
    - coveralls
